### ISSUE TITLE
Flag --policy-config-file not supported in K8s version starting from v1.23

### ISSUE THREAD

**Issue by mknnj** [elastic-ai/elastic-gpu-scheduler#12]
As referred in https://kubernetes.io/docs/reference/scheduling/policies/ from v1.23 of Kubernetes the `--policy-config-file `flag for the kube scheduler is not supported anymore. 
By following the instructions in `readme.md` you will get an error in `kube-scheduler` logs that tells you that.
The solution to this is to use the flag `--config=/etc/kubernetes/scheduler-policy-config.yaml` and to create a file `scheduler-policy-config.yaml` compliant to KubeSchedulerConfiguration requirements.
I tried converting the file `scheduler-policy-config.json` that was suggested to use in the `readme.md` and i got this `scheduler-policy-config.yaml` :
```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
extenders:
- urlPrefix: "http://< ip >:39999/scheduler"
  filterVerb: filter
  prioritizeVerb: priorities
  bindVerb: bind
  weight: 1
  enableHTTPS: false
  nodeCacheCapable: true
  managedResources:
  - name: nano-gpu/gpu-percent
```

And now everything works fine.
I think it would be nice to add this in the readme.md for latest versions of K8s.
